name: CI Pipline
on:
  push:
    branches : [main]
  pull_request:
    branches : [main]
job:
  test:
    runs-on: ubantu-latest
    steps:
      -name: Checkout the code
      uses: actions/checkout@v2

      -name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      -name: Install dependencies
      run: npm ci
      -name: Run tests
      run: npm test
      




